"use client"

import { createContext, useContext, useState, useEffect, useCallback, type ReactNode } from "react"

export type Theme = "light" | "dark-fintech" | "dark-terminal"

const STORAGE_KEY = "portafolio-theme-v1"
const DEFAULT_THEME: Theme = "light"

interface ThemeContextValue {
  theme: Theme
  setTheme: (theme: Theme) => void
}

const ThemeContext = createContext<ThemeContextValue | null>(null)

export function ThemeProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<Theme>(DEFAULT_THEME)

  useEffect(() => {
    // Try to load from config.json first (generated by SKILL.md)
    fetch("/data/config.json")
      .then((res) => res.ok ? res.json() : null)
      .then((config) => {
        if (config?.theme && ["light", "dark-fintech", "dark-terminal"].includes(config.theme)) {
          setThemeState(config.theme as Theme)
          return
        }
        // Fallback to localStorage
        const stored = localStorage.getItem(STORAGE_KEY) as Theme | null
        if (stored && ["light", "dark-fintech", "dark-terminal"].includes(stored)) {
          setThemeState(stored)
        }
      })
      .catch(() => {
        const stored = localStorage.getItem(STORAGE_KEY) as Theme | null
        if (stored && ["light", "dark-fintech", "dark-terminal"].includes(stored)) {
          setThemeState(stored)
        }
      })
  }, [])

  useEffect(() => {
    document.documentElement.setAttribute("data-theme", theme)
    localStorage.setItem(STORAGE_KEY, theme)
  }, [theme])

  const setTheme = useCallback((newTheme: Theme) => {
    setThemeState(newTheme)
  }, [])

  return (
    <ThemeContext.Provider value={{ theme, setTheme }}>
      {children}
    </ThemeContext.Provider>
  )
}

export function useTheme(): ThemeContextValue {
  const ctx = useContext(ThemeContext)
  if (!ctx) throw new Error("useTheme must be used within a ThemeProvider")
  return ctx
}
